### PR TITLE
Fix orientation pb + Dynamical filter initialization

### PR DESCRIPTION
**Pull request by olivier-stasse**
This PR fix two important bugs:
 * Fix orientation pb with Naveau 2015: The orientation was not appropriately initialized at the end of the algorithm. The CurrentConfiguration vector is now appropriatly set.
* Fix the starting phase of the dynamical filter and more precisely inside the  ZMPPreviewControlWithMultiBodyZMP class.

It also implements the following 
 * The corresponding unit tests are put back and updated.
 * It implements a flag to reduce the number of tests such that the CI can test them in DEBUG mode. Naveau2015 is 20 times slower in this mode. Fix issue #13 
 * Warning messages number has been reduced.

### CODE REVIEW

**Comment by olivier-stasse** [comment]
This PR has been tested on https://gepgitlab.laas.fr/ostasse/jrl-walkgen/pipelines/9184

**Comment by nim65s** [comment]
Overall this looks good to me, but I need some time to clean this a bit.

**Comment by olivier-stasse** [comment]
Would that be ok if we accept the PR and then you add the commit for cleaning the code.
Cleaning jrl-walkgen is a massive work.

**Comment by nim65s** [comment]
No, I'm intending to clean the git history of this PR, not the code :)

**Comment by olivier-stasse** [comment]
Yes that would be fantastic, I tried but failed and had to resort to merge instead of rebase.

**Comment by olivier-stasse** [comment]
Thx Guilhem.

**Pull request closed without merging**
